### ISSUE TITLE
Application Area functions no longer work with the last build version?

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/ALAppExtensions#1679]
In our extension we use the functions "GetApplicationAreaBuffer" and "TrySaveApplicationAreaCurrentCompany" from the code unit "Application Area Mgmt.". We have now built a new docker container with version 

- Version: 14.0.29313.0-DE
- Platform: 14.0.29286.0

 and wanted to release the app there. But that didn't work. There are now two messages saying that these methods can no longer be used. Here are again exactly the errors that come:

- The type or method 'GetApplicationAreaBuffer' cannot be used for 'Extension' development.
- The type or method 'TrySaveApplicationAreaCurrentCompany' cannot be used for 'Extension' development.

Has anything been changed here? Why can't you use these methods all of a sudden? How else can you work with the application areas if you are not allowed to use the methods?

**Comment by JesperSchulz** [comment]
We'll look into it and get back to you.

**Comment by grobyns** [comment]
Hi,

all available functions for Application Areas are in Codeunit 9179 Application Area Mgmt. Facade. The functions in Codeunit 9178 Application Area Mgmt. were incorrectly marked as External and this was corrected.

Specifically:
- you should not need to access the buffer table. I would be interested in understanding the scenario where you are accessing the buffer table to evaluate if we are missing something there. 

- Application Areas are not meant to be set directly. Instead, they should be assigned to an Experience Tier and the Experience Tier is what sets the relevant Application Areas. When a new version is pushed out, the selected Experience Tier is refreshed and its Application Areas are reset. This is to ensure that new areas added get initialized correctly according to the Experience Tier they are assigned to. For this reason, you should not bypass the Experience Tier but instead assign your added application areas (or existing ones) to the correct Experience Tier and set the Experience Tier which will then control whether the area is enabled or disabled.

br/Gert

**Comment by FSharpCSharp** [comment]
> all available functions for Application Areas are in Codeunit 9179 Application Area Mgmt. Facade. The functions in Codeunit 9178 Application Area Mgmt. were incorrectly marked as External and this was corrected.

OK, that's of course bad that it is. We have made an adjustment in our extension here, because the page 9179 is marked the column "Selected" as editable, and there is also logic contained to initialize certain application areas. But this doesn't work because the entire page also has the property "ModifyAllowed" set to false. Thus the column is not editable. However, our customers wanted to activate certain application areas. And so we moved a copy of this page to our extension, where we made all the standard functions available. Thus it was possible for our customers to activate further application areas independently.

> * you should not need to access the buffer table. I would be interested in understanding the scenario where you are accessing the buffer table to evaluate if we are missing something there.

And then how can you use the program to find out whether a particular application area is active at all without this table? 

> * Application Areas are not meant to be set directly. Instead, they should be assigned to an Experience Tier and the Experience Tier is what sets the relevant Application Areas. When a new version is pushed out, the selected Experience Tier is refreshed and its Application Areas are reset. This is to ensure that new areas added get initialized correctly according to the Experience Tier they are assigned to. For this reason, you should not bypass the Experience Tier but instead assign your added application areas (or existing ones) to the correct Experience Tier and set the Experience Tier which will then control whether the area is enabled or disabled.

But our customers want to be able to activate this. In the cloud, the "Advanced" application area is deactivated by default. And they want to be able to activate it at the push of a button. But due to the bug in the standard that the page 9179 pretends to be able to change something here, but you can't, it was not otherwise possible for us to satisfy the customer.

**Comment by grobyns** [comment]
Hi,

If all that is needed is to enable the Advanced area then I would recommend adding it to the Premium experience or add a new Premium+Advanced experience.
For other scenarios I would recommend creating new Experience Tiers for the most common combinations of application areas.

To programmatically know which areas are enabled/disabled you can either check the application area setup table or use one of the many Is<Area>Enabled functions. 
 
br/Gert

**Comment by FSharpCSharp** [comment]
Unfortunately, that didn't work out. We also played around with the premium experience in Docker. "Advanced" was still not active here either. Is there perhaps any other place where you can do that? We searched the whole application but couldn't find anything.

And that with the examination of all application areas is very cumbersome. So this was the simplest and most satisfying option for the customer.

The whole issue of application areas is currently causing our customer to feel uncomfortable because it is not easy to manage them. Also the experience tiers which you have addressed solve this only conditionally and did not really satisfy our customer.

**Comment by grobyns** [comment]
To enable Advanced anywhere you need to enable it in code. You will need to add a subscriber to the OnGetPremiumExperienceAppAreas event where you enable the Advanced area.

You can read a little more about it here:
[Adding Advanced application area to the Essentials and Premium experiences using an extension](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-application-areas#adding-advanced-application-area-to-the-essentials-and-premium-experiences-using-an-extension)

br/Gert

**Comment by FSharpCSharp** [comment]
We had already tried this, but it didn't work. But you can't really be serious about that, can you? Why can't you activate it conveniently on the user interface? No normal user understands that, and neither do we as developers. We even tried the example you linked to in the cloud as well as in a docker sandbox. But the application area was still not active. It was only with the methods mentioned above that we were able to activate it at all.

**Comment by grobyns** [comment]
Have you tried changing experience on the Company Information card? Perhaps you are missing a session refresh... When switching on company info, there's a session refresh when you close the card...
