### ISSUE TITLE
[Request for Access] Sent E-Mail Attachments

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#22167]
Hello there,
we would like to archive the sent e-mail attachments externally. 
-> We want to delete the attachment content after archiving and write the link (to the archived file) back to the attachments.

But the table 8904 "Email Message Attachment" is internal and the function to delete the content of the attachments only works if the email has not been sent yet. The error is triggered by a modify on the email message:

Callstack:
-> Attachments_DeleteContent
--> OnModify()
---> OnBeforeModifyEmailMessage
-----> Error(EmailMessageSentCannotModifyErr); 

This means we can neither directly nor indirectly delete the attachments, nor create a new field in the table.

We would like to propose the following:
- The table becomes public and, if necessary, only certain fields remain internal. Therefore we could address every attachment by its id and add the link to the external archive.
- You add a second function named "Attachments_DeleteContent" with the parameter "AttachmentId: BigInteger" to address the specific attachment and delete its content.
- Add the possibility to turn off the check for sent emails during the process, e.g. via an OnBeforeCheckForSentEmail-Publisher with IsHandled-Flag.

Please let us know if you need further information.
Thank you very much in advance!

**Comment by pri-kise** [comment]
@GOB-Andrea this isn't the first time, that some requests this for the Sent E-Mail tables.
How do would you deal with the process that an sent e-Mail can be resend?

Would it be better if there would be an interface for this specific scenario with the following required methods:
- ArchiveAttachment() : Coderunit "TODO External Reference"// Archives the Attachment at an external ressource and returns some details of the external reference
- GetAttachment() // Download Attachment from the Sent Mail and used to create a new Mail as copy of the sent E-mail

Parts of the system application: Provide a process to archive the attachments of sent E-mails and update to UI to show links or similiar to the external ressource.

**Comment by GOB-Andrea** [comment]
Hi @pri-kise, for resending an e-mail that has already been sent, we would either
A: use the link we have stored to load the attachments from the archive system and attach them directly to the new email.
B: use the link we have stored to temporarily load the attachments from the archive system into the sent e-mail attachments, so that they are "automatically" attached to the new e-mail. (Variant B is probably not possible at present due to the existing access restrictions.)

Some kind of interface to connect to an external system for archiving attachments is a possible idea. I see two methods there as well
- A function to archive the attachments (as you said)
- A function for restoring the attachments in the sent e-mail or temporarily download the attachment to add them to the new e-mail

However, we would still have the same requirements as mentioned above:
- We need access to the ID and the content of the email attachments. 
- It must be possible to disable the error message when deleting the content. 
- A field to create a link to the archive must be available or addable.

**Comment by AlexanderYakunin** [comment]
You requested the change for system app, so I forward this to Foundation team.

**Comment by dam-pav** [comment]
Hi all,

This issue was supposedly resolved with #10254, which was opened by @GOB-Andrea him/herself. 

I can deduce and speculate that the solution introduced was never really tested and confirmed  in a real use case. The procedure _"Email Message Impl."(CodeUnit 8905).Attachments_DeleteContent_ calls _"Email Message Impl."(CodeUnit 8905).Modify_ which, further down the callstack, triggers _"Email Message Impl."(CodeUnit 8905).OnBeforeModifyEmailMessage_. 

The _OnBeforeModifyEmailMessage_ subscriber was there all along since v17 preventing any modification to "Sent Emails". 

The way I see this we could go down two roads:
1. Keep the attachment table isolated but enhance the _Attachments_DeleteContent_ call with the ability to override the validation.
2. Forget _Attachments_DeleteContent_, expose the table and let developers take responsibility for the attachments.

**Comment by darjoo** [comment]
Hi all,

We have provided the following in the `Email Message` codeunit.

An overload `Attachments_DeleteContent(BypassSentCheck: Boolean)`, `Attachments_Delete()` and `Attachments_Delete(BypassSentCheck: Boolean):`

`DeleteContent`: This will specifically only delete the contents (Tenant Media), however the `Email Message Attachment` record will still exist. So the user can see what attachment used to be there. The file size becomes 0, as it no longer links to an actual file.

`Delete`: This will delete both the contents and the `Email Message Attachment` record.

It will be in for 23.1 minor release.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12152.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 12333.
